homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 0
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Amsterdam
  # Customization file
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
    - type: trusted_networks

automation: !include_dir_merge_list automations/
group: !include_dir_merge_named groups/
#script: !include scripts.yaml
#
# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:
  themes:
    PmxMononight:
      # MyVariables
      base-hue: '220' #Controls the base (and accent) color hue (0-360) | 0=Red 60=Yellow 120=Green 180=Cyan 240=Blue 300=Magenta 360=Red
      base-sat: '16%' #Controls the saturation of the theme (0%-100%) | 0%=Grey 100%=Full Saturation
      # MyVar
      huesat: 'var(--base-hue), var(--base-sat),'
      # Primary Color
      primary-color: 'hsl(var(--huesat) 20%)'
      # Backgrounds
      primary-background-color: 'var(--primary-color)'
      secondary-background-color: 'hsl(var(--huesat) 16%)'
      paper-listbox-background-color: 'var(--primary-color)'
      paper-card-background-color: 'hsl(var(--huesat) 12%)'
      paper-dialog-background-color: 'var(--paper-card-background-color)'
      table-row-background-color: 'hsl(var(--huesat) 12%)'
      table-row-alternative-background-color: 'hsl(var(--huesat) 10%)'
      # Devider
      divider-color: 'hsla(0, 0%, 0%, 0)'
      dark-divider-opacity: '0'
      light-divider-opacity: '0'
      # Text colors
      primary-text-color: 'hsl(var(--huesat) 60%)'
      text-primary-color: 'hsl(var(--huesat) 60%)'
      secondary-text-color: 'hsl(var(--huesat) 60%)'
      disabled-text-color: 'hsl(var(--huesat) 70%)'
      sidebar-text_-_color: 'hsl(var(--huesat) 90%)'
      sidebar-text-color: 'hsl(var(--huesat) 90%)'
      paper-card-header-color: 'hsl(var(--base-hue), 90%, 50%)'
      # Text Adjustments
      paper-font-headline_-_letter-spacing: '-0.5px'
      paper-font-headline_-_font-weight: '500'
      paper-font-body1_-_font-weight: '500'
      # Nav Menu
      paper-listbox-color: 'hsl(var(--huesat) 50%)'
      paper-grey-50: 'hsl(var(--huesat) 50%)'
      paper-grey-200: 'hsla(var(--huesat) 26%)'
      # Paper card
      paper-item-icon-color: 'hsl(var(--huesat) 30%)'
      paper-item-icon-active-color: 'var(--paper-item-icon-color)'
      paper-item-icon_-_color: 'var(--paper-item-icon-color)'
      paper-item-selected_-_background-color: 'hsla(0, 0%, 0%, 0.2)'
      paper-tabs-selection-bar-color: 'hsla(0, 0%, 0%, 0.2)'
      # Labels
      label-badge-red: 'hsla(0, 0%, 0%, 0)'
      label-badge-border-color: 'var(--label-badge-red)'
      label-badge-background-color: 'var(--paper-card-background-color)'
      label-badge-text-color: 'var(--primary-text-color)'
      # Shadows
      shadow-elevation-2dp_-_box-shadow: 'inset 0px 0px 0px 4px hsl(var(--huesat) 18%)'
      shadow-elevation-16dp_-_box-shadow: 'inset 0px 0px 0px 4px hsl(var(--huesat) 28%)'
      # Switches
      paper-toggle-button-checked-button-color: 'hsl(var(--base-hue), 90%, 50%)'
      paper-toggle-button-checked-bar-color: 'hsl(var(--huesat) 25%)'
      paper-toggle-button-unchecked-button-color: 'hsl(var(--huesat) 25%)'
      paper-toggle-button-unchecked-bar-color: 'hsl(var(--huesat) 5%)'
      # Sliders
      paper-slider-knob-color:  'hsl(var(--base-hue), 90%, 50%)'
      paper-slider-knob-start-color: 'hsl(var(--base-hue), 80%, 25%)'
      paper-slider-pin-color:  'hsl(var(--base-hue), 90%, 50%)'
      paper-slider-active-color:  'hsl(var(--base-hue), 90%, 50%)'
      paper-slider-container-color: 'hsl(var(--huesat) 28%)'
      paper-slider-secondary-color: 'hsl(var(--huesat) 90%)'
      paper-slider-disabled-active-color: 'hsl(var(--base-hue), 80%, 25%)'
      paper-slider-disabled-secondary-color: 'hsl(var(--base-hue), 80%, 25%)'
      paper-dialog-color: 'hsl(var(--base-hue), 20%, 80%)'


    Night_Theme:
      # Main Stuff #
      primary-color: "#0179d8" # Primary (most of the UI)
      primary-background-color: "#060606" # Primary background colour (dialogs, e.t.c)
      secondary-background-color: "#060606" # Secondary background colour (main UI background)
      paper-card-background-color: "#131313" # Card background colour
      paper-item-icon-color: "#0179d8" # Icon colour
      primary-text-color: "#FFFFFF" # Primary text colour
      secondary-text-color: "rgba(255, 255, 255, 0.5)" # Secondary text colour
      disabled-text-color: "rgba(255, 255, 255, 0.5)" # Disabled text colour
      divider-color: "rgba(255, 255, 255, 0.12)" # Divider colour
      paper-card-header-color: "#FFFFFF" # Card header text colour

      # Nav Menu #
      paper-listbox-background-color: "#131313" # Listbox background colour
      paper-listbox-color: "#FFFFFF" # Listbox text colour
      paper-grey-200: "#060606" # Listbox selected item background colour

      # Switches #
      paper-toggle-button-checked-ink-color: "#d80129"
      paper-toggle-button-checked-button-color: "#0179d8"
      paper-toggle-button-checked-bar-color: "#FFFFFF"

      # Sliders #
      paper-slider-knob-color: "#0179d8"
      paper-slider-knob-start-color: "#0179d8"
      paper-slider-pin-color: "#0179d8"
      paper-slider-active-color: "#0179d8"
      paper-slider-secondary-color: "#0179d8"

      # Tables #
      table-row-background-color: transparant
      table-row-alternative-background-color: transparant

#mini players
  extra_html_url:
    - /local/custom_ui/state-card-mini-media-player.html
  extra_html_url_es5:
    - /local/custom_ui/state-card-mini-media-player_es5.html
    
input_text:
  media_spotify:
    name: Spotify
  media_woonkamertv:
    name: Woonkamer TV
  media_soundbar_woonkamer:
    name: Woonkamer soundbar
  media_chromecast_woonkamer:
    name: Woonkamer chromecast

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
#  base_url: assistant.home.wijnand.top:443
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 192.168.1.0/24
    - fd00::/8

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# Tracked history is kept for 10 days
recorder:
  purge_interval: 2
  purge_keep_days: 30
  db_url: !secret db_connection_string


# View all events in a logbook
logbook:

splunk:
  token: !secret splunk_token
  host: 192.168.1.44
#  port: 8000
# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor: !include sensors.yaml
weather:
  - platform: buienradar
  
# Text to speech
tts:
  - platform: google

# Cloud
cloud:


media_player:
#  - platform: braviatv
#    name: Woonkamer TV
#    host: 192.168.1.26
  - platform: spotify
    client_id: 7ad666bc74af45cdb3d91a8683f0baaa
    client_secret: !secret spotify_client_secret
  - platform: cast
  - platform: philips_js
    name: Keuken TV
    host: 192.168.1.37
  - platform: philips_js
    name: Slaapkamer TV
    host: 192.168.1.32

camera:
  - platform: synology
    url: !secret synology_url
    username: !secret synology_username
    password: !secret synology_password
    timeout: 15
    verify_ssl: False

notify:
  - platform: nfandroidtv
    name: Woonkamer TV
    host: 192.168.1.26

zwave:
  usb_path: /dev/ttyACM0

ios:

zone:
  - name: Praktijk
    latitude: 52.026944
    longitude: 5.542693
    radius: 200
    icon: mdi:domain
    track_ios: true

  # This will override the default home zone
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 200
    icon: mdi:home-heart
    track_ios: true

scene:
  - name: Romantic
    entities:
      switch.neoswitch1_switch: on

cover:
  - platform: template
    covers:
      curtains_bedroom:
        friendly_name: "Slaapkamer gordijnen"
        value_template:  "{{ states.switch.neoswitch1_switch.state == 'on' }}"
        open_cover:
          service: switch.turn_on
          entity_id: switch.neoswitch1_switch
        close_cover:
          service: switch.turn_off
          entity_id: switch.neoswitch1_switch
        icon_template: >-
          {% if states.switch.neoswitch1_switch.state == 'on' %}
            mdi:garage-open
          {% else %}
            mdi:garage
          {% endif %}

light:
  - platform: template
    lights:
      switch_light:
        friendly_name: "Switch light"
        value_template: "{{ states.switch.neoswitch1_switch.state == 'on' }}"
        turn_on:
          service: switch.turn_on
          entity_id: switch.neoswitch1_switch
        turn_off:
          service: switch.turn_off
          entity_id: switch.neoswitch1_switch

history_graph:
  home_energy:
    entities:
      - switch.switch_4
      - sensor.neo_coolcam_power_plug_12a_power_2

neato:
  username: !secret neat_username
  password: !secret neato_password

logger:
  default: info
  logs:
      custom_components: debug

gardena:
  username : !secret gardena_user
  password : !secret gardena_password


panel_custom:
  - name: zwavegraph2
    sidebar_title: ZWave Graph2
    sidebar_icon: mdi:access-point-network
    url_path: zwave

panel_iframe:
  influxdb:
    title: InfluxDB
    icon: mdi:chart-areaspline
    url: http://homeassistant.local:8888

lovelace:
  mode: yaml

influxdb:
  host: 192.168.1.44
  port: 8086
  database: homeassistant
  username: homeassistant
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state